### ISSUE TITLE
`AttributeError: 'int' object has no attribute 'lower'`

### ISSUE THREAD

**Issue by evandrix** [kohnakagawa/impfuzzy_lief#1]
getting an error here https://github.com/kohnakagawa/impfuzzy_lief/blob/master/src/impfuzzy_lief/core.py#L40 when running the code

the reason is obvious - `api.ordinal` is a numeric integer, not a string, so it cannot be lowercase'd

is this a typographical error?

**Comment by kohnakagawa** [comment]
@evandrix Thank you. Of course, this is a typographical error. I fixed this.

**Comment by evandrix** [comment]
:+1:
