### ISSUE TITLE
*.drv?

### ISSUE THREAD

**Issue by evandrix** [kohnakagawa/impfuzzy_lief#2]
https://github.com/kohnakagawa/impfuzzy_lief/blob/master/src/impfuzzy_lief/core.py#L10
`exts = ("ocx", "sys", "dll")`

might want to either include additional file extension e.g. `.drv` as in `winspool.drv`, or to just strip file extensions altogether i.e. `pathlib.Path(dllname).stem`

sample in question is attached
[65860a5486c5d7597d69339d6ca9d4c104508834.bin.zip](https://github.com/kohnakagawa/impfuzzy_lief/files/4694176/65860a5486c5d7597d69339d6ca9d4c104508834.bin.zip)

**Comment by kohnakagawa** [comment]
Thank you for submitting this issue.

This repository is the re-implementation of [impfuzzy](https://github.com/JPCERTCC/impfuzzy/tree/master/pyimpfuzzy) by JPCERTCC. In their project, `*.drv` is not included as follows.

https://github.com/JPCERTCC/impfuzzy/blob/d83d64d7fa58f1c5d50c21b18a018bb094c58fb8/pyimpfuzzy/pyimpfuzzy.py#L31-L38

Therefore, I do not include `drv` extension in this project.
